// File generated by `flutterfire configure` — DO NOT EDIT manually.
// Once the project is connected to a Firebase project via:
//   cd mobile && flutterfire configure
// this file will be regenerated with the correct credentials.
//
// Until then, DummyFirebaseOptions is used so the app compiles without
// google-services.json / GoogleService-Info.plist present.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Dummy options used when Firebase credentials have not yet been configured.
/// Replace this class entirely by running `flutterfire configure`.
class DummyFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return const FirebaseOptions(
        apiKey: 'DUMMY_API_KEY',
        appId: 'DUMMY_WEB_APP_ID',
        messagingSenderId: 'DUMMY_SENDER_ID',
        projectId: 'real-estate-crm-dummy',
        authDomain: 'real-estate-crm-dummy.firebaseapp.com',
        storageBucket: 'real-estate-crm-dummy.appspot.com',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return const FirebaseOptions(
          apiKey: 'DUMMY_ANDROID_API_KEY',
          appId: 'DUMMY_ANDROID_APP_ID',
          messagingSenderId: 'DUMMY_SENDER_ID',
          projectId: 'real-estate-crm-dummy',
          storageBucket: 'real-estate-crm-dummy.appspot.com',
        );
      case TargetPlatform.iOS:
        return const FirebaseOptions(
          apiKey: 'DUMMY_IOS_API_KEY',
          appId: 'DUMMY_IOS_APP_ID',
          messagingSenderId: 'DUMMY_SENDER_ID',
          projectId: 'real-estate-crm-dummy',
          storageBucket: 'real-estate-crm-dummy.appspot.com',
          iosBundleId: 'com.example.realEstateCrm',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
}

/// In production this will be `DefaultFirebaseOptions.currentPlatform`
/// generated by `flutterfire configure`.
FirebaseOptions getFirebaseOptions() => DummyFirebaseOptions.currentPlatform;